name: Compile and minify source code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "14"

      - name: Install luamin
        run: npm install -g luamin

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v9

      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install luacc
        run: luarocks install luacc

      - name: Compile Lua files
        run: sh ./compile.sh
